
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>ModdersToolkit</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CodeAnalysis.CSharp.Scripting">
      <HintPath>lib\Microsoft.CodeAnalysis.CSharp.Scripting.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis.Scripting">
      <HintPath>lib\Microsoft.CodeAnalysis.Scripting.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>